### ISSUE TITLE
TODO checklist for 2022

### ISSUE THREAD

**Issue by jonathancallahan** [pnwairfire/known-locations#1]
Items as they come up:

-----
_TODO:_

- [ ] Using `MazamaLocationUtils::location_getOpenCageInfo()` brought in 3-char state codes for Mexico. These need to revert to 2-char codes to be consistent with **MazamaSpatialUtils**. (1/18)
- [ ] Move master tables to AWS RDS tables and have all script updates pull/push from there. This will involve code in the **monitoring-data-ingest-v2** repository. This will allow a non-R user to manually update location names, etc. (7/18)
- [ ] Always uses sites v2 metadata names as the official location_display_name. (8/15)

----
_Items finished on 2022-07-18_

- [x] Set up TODO checklist. (7/18)
